{
  "hash": "6c26b205506367ecb76a94cefc346280",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Half-Life of a Market Edge\"\nsubtitle: \"Post-publication alpha decay across 189 equity anomalies, 1926–2024\"\nauthor: \"Mehmet Tuğsuz\"\ndate: today\nabstract: |\n  Several hundred cross-sectional return predictors have been published since the 1980s.\n  If they are compensation for risk, publication should not change them; if they are\n  mispricing, publication is the moment enough capital learns about them to trade them\n  away. Across the 189 usable signals in the Chen–Zimmermann universe (1926–2024,\n  173,302 signal-months) the mean monthly long-short return falls 45% after publication\n  and the median signal loses 53%, updating McLean and Pontiff (2016). The paper then\n  tests, rather than asserts, the restriction that separates the arbitrage channel from\n  the data-mining channel, and fails to reject equality — so the three-window design\n  does not identify the channel on this universe. Two of the input series are rebuilt\n  from raw CRSP as a check on the whole exercise.\n---\n\n::: {.callout-note appearance=\"simple\"}\n**This document is the project, not a summary of it.** Every number in the prose is\ncomputed by a code chunk below or read out of a committed result file; none is typed by\nhand. The order is deliberate: the question, then the estimand, then the estimator\nwritten out, then the number, then the test that the number survives.\n\nSource: [`github.com/tugsuz/alpha-decay`](https://github.com/tugsuz/alpha-decay).\nSections @sec-question through @sec-restriction need only the free Chen–Zimmermann\nfiles; @sec-rebuild reads committed results and needs nothing at all.\n:::\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"setup: paths, plotting defaults, helpers\"}\nfrom pathlib import Path\nimport numpy as np\nimport pandas as pd\nimport matplotlib as mpl\nimport matplotlib.pyplot as plt\nfrom IPython.display import Markdown\n\nROOT = Path.cwd().parent if Path.cwd().name == \"paper\" else Path.cwd()\nDATA, OUT = ROOT / \"data\", ROOT / \"output\"\n\nHAVE_CZ = (DATA / \"PredictorLSretWide.csv\").exists() and (DATA / \"SignalDoc.csv\").exists()\n\n# Two categorical hues, validated for colour-vision deficiency against a light surface\n# (worst-pair CVD ΔE 9.2, normal-vision ΔE 24.0). Identity is never carried by colour\n# alone: every two-series figure also gets a legend and direct end labels.\nBLUE, ORANGE = \"#2a78d6\", \"#eb6834\"\nINK, MUTED, GRID = \"#0b0b0b\", \"#52514e\", \"#d9d9d6\"\n\nmpl.rcParams.update({\n    \"figure.facecolor\": \"white\", \"axes.facecolor\": \"white\",\n    \"axes.edgecolor\": MUTED, \"axes.labelcolor\": INK, \"text.color\": INK,\n    \"xtick.color\": MUTED, \"ytick.color\": MUTED,\n    \"axes.spines.top\": False, \"axes.spines.right\": False,\n    \"axes.grid\": True, \"grid.color\": GRID, \"grid.linewidth\": 0.6,\n    \"font.size\": 9.5, \"axes.titlesize\": 10.5, \"axes.titlelocation\": \"left\",\n    \"legend.frameon\": False, \"figure.dpi\": 160,\n})\n\ndef ym(mi):\n    \"\"\"Invert mi = year*12 + month.\n\n    Month runs 1..12, so December has mi % 12 == 0 and mi // 12 == year + 1. Decoding\n    with (mi // 12, mi % 12 or 12) is right eleven months out of twelve and files every\n    December under the following year. divmod on mi - 1 has no such seam.\n    \"\"\"\n    y, m = divmod(int(mi) - 1, 12)\n    return y, m + 1\n\ndef mi_to_ts(idx):\n    return pd.to_datetime([f\"{y}-{m:02d}-01\" for y, m in map(ym, idx)])\n\nimport matplotlib.patheffects as pe\nHALO = [pe.withStroke(linewidth=2.6, foreground=\"white\")]   # keeps labels legible on marks\n\ndef fmt(x, d=3):\n    return f\"{x:,.{d}f}\"\n```\n:::\n\n\n# The question {#sec-question}\n\nA cross-sectional return predictor is a rule that sorts stocks on some characteristic\nand goes long one end and short the other. Several hundred have been documented since\n@banz1981, enough that @harvey2016 argue the conventional *t*-statistic hurdle of 2.0 is\nfar too low for a literature that has run this many tests, and @hou2020 find that a\nmajority do not survive careful replication.\n\nThat is a statement about the *past* of a signal. This project is about its *future*.\nTake a predictor that was real in its original sample and ask what happens to it after\nthe paper appears. Two stories predict opposite things.\n\n**Arbitrage.** The edge was mispricing. Publication makes it common knowledge, capital\narrives, the mispricing is traded away. @mclean2016 call this the out-of-sample\npublication effect, and it is the mechanism in @shleifer1997: the edge shrinks, but not\nnecessarily to zero, because @grossman1980 requires a positive residual return to pay\nfor the arbitrage in the first place. A market in which every published edge went to\nexactly zero would be one in which nobody was paid to look, and the edges would return.\n\n**Data mining.** The edge was never there. The original sample was lucky — selected, over\nfitted, or the survivor of a search across many candidate characteristics that were never\nreported. Then the edge does not wait for publication to disappear; it is already gone\nthe moment you step outside the sample the author chose.\n\nBoth predict decay. They differ in *when*, and that is what makes the design in\n@sec-design a test rather than a description.\n\n# Data {#sec-data}\n\n## The anomaly universe\n\n@chen2022 reimplement several hundred published predictors from their original papers and\npublish the resulting long-short portfolio return series together with a documentation\nfile recording, for each signal, the authors, the journal, the publication year, the\noriginal sample window and the implementation parameters. Two files are used here, both\nfree:\n\n| File | What it holds |\n|---|---|\n| `PredictorLSretWide.csv` | monthly long-short returns, one column per signal |\n| `SignalDoc.csv` | one row per signal: acronym, journal, `Year`, `SampleStartYear`, `SampleEndYear`, plus `Sign`, `Stock Weight`, `LS Quantile`, `Portfolio Period` |\n\n**Release: October 2025, v2.0.0.** Most series run through December 2024;\noption-implied-volatility predictors end December 2022. This is the first release\nproduced by the authors' Python translation rather than the original Stata code, and\n`ChNAnalyst`, `PriceDelayTstat` and `Recomm_ShortInterest` carry revisions from bug fixes\nin that translation. All three are in the universe below.\n\n::: {#load .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"load the two Chen–Zimmermann files\"}\nif not HAVE_CZ:\n    raise SystemExit(\n        \"data/PredictorLSretWide.csv and data/SignalDoc.csv are missing.\\n\"\n        \"Both are free from https://www.openassetpricing.com (Data tab). \"\n        \"Put them in data/ and render again.\"\n    )\n\nrets = pd.read_csv(DATA / \"PredictorLSretWide.csv\")\nrets = rets.rename(columns={rets.columns[0]: \"date\"})\nrets[\"date\"] = pd.to_datetime(rets[\"date\"])\ndoc = pd.read_csv(DATA / \"SignalDoc.csv\")\n```\n:::\n\n\n## Which signals enter, and why\n\nThree filters, each of which changes the answer and therefore belongs in the text rather\nthan in a footnote.\n\n1. **Predictors only.** The authors label some series as placebos — characteristics their\n   own replication finds do not predict. Averaging those in would drag every window\n   towards zero and flatter the decay.\n2. **The paper's sample must end strictly before the paper appears.** If it does not,\n   window 2 below has no months in it and the three-window design collapses to two.\n3. **At least 24 monthly observations in *every* window.** Otherwise a signal can enter\n   the post-publication average on the strength of three observations.\n\nThe third filter is what makes the headline comparison honest: the *same* signals appear\nin all three windows, so the decline cannot be an artefact of the composition changing\nbetween them.\n\n::: {#panel .cell execution_count=3}\n``` {.python .cell-code code-fold=\"false\"}\nMIN_MONTHS = 24\n\nd = doc[doc[\"Cat.Signal\"] == \"Predictor\"].dropna(subset=[\"Year\", \"SampleEndYear\"])\nd = d[d[\"SampleEndYear\"] < d[\"Year\"]]                       # filter 2\n\nusable = [c for c in rets.columns if c != \"date\" and c in set(d[\"Acronym\"])]\nlong = (rets[[\"date\"] + usable]\n        .melt(id_vars=\"date\", var_name=\"signal\", value_name=\"ret\")\n        .dropna(subset=[\"ret\"]))\n\nmeta = d.set_index(\"Acronym\")[[\"Year\", \"SampleEndYear\"]]\nlong[\"pub_year\"] = long[\"signal\"].map(meta[\"Year\"]).astype(int)\nlong[\"samp_end\"] = long[\"signal\"].map(meta[\"SampleEndYear\"]).astype(int)\nlong[\"year\"] = long[\"date\"].dt.year\n\nlong[\"window\"] = np.select(\n    [long[\"year\"] <= long[\"samp_end\"],\n     (long[\"year\"] > long[\"samp_end\"]) & (long[\"year\"] < long[\"pub_year\"])],\n    [\"1_in_sample\", \"2_post_sample\"],\n    default=\"3_post_pub\",\n)\n```\n:::\n\n\n::: {#matched .cell execution_count=4}\n``` {.python .cell-code code-fold=\"false\"}\ng = long.groupby([\"signal\", \"window\"])[\"ret\"].agg([\"mean\", \"size\"]).unstack(\"window\")\ncomplete = (g[\"size\"].fillna(0) >= MIN_MONTHS).all(axis=1)      # filter 3\ntable = g[\"mean\"][complete].dropna()\ntable.columns = [c.split(\"_\", 1)[1] for c in table.columns]\n\nN_MATCHED = len(table)\nN_PANEL   = long[\"signal\"].nunique()\nN_OBS     = len(long)\nN_DATES   = long[\"date\"].nunique()\n```\n:::\n\n\nThe panel used for the regression holds 212 signals and\n173\\,302 signal-months over\n1926\\-01 to 2024\\-12,\nacross 1\\,188 distinct months. The matched table holds the\n189 signals that clear all three filters.\n\n# Design: three windows {#sec-design}\n\nCut each signal's history at two dates taken from its own paper:\n\n| Window | Definition | What it is |\n|---|---|---|\n| 1. in-sample | year ≤ `SampleEndYear` | the edge as originally reported |\n| 2. post-sample | `SampleEndYear` < year < `Year` | discovered, not yet public |\n| 3. post-publication | year ≥ `Year` | public, and being traded on |\n\nWindow 2 is the whole design. Under the arbitrage story nothing happens until the paper\nappears, so window 2 should look like window 1 and only window 3 falls. Under the\ndata-mining story window 2 is *already* lower, because stepping outside the author's\nchosen sample is enough.\n\nWrite the estimand as a within-signal comparison of means. For signal $i$ let\n$\\mu_i^{(w)}$ be its mean long-short return in window $w$. Then\n\n$$\n\\delta_1 \\;=\\; \\mathbb{E}_i\\!\\left[\\mu_i^{(2)} - \\mu_i^{(1)}\\right],\n\\qquad\n\\delta_2 \\;=\\; \\mathbb{E}_i\\!\\left[\\mu_i^{(3)} - \\mu_i^{(1)}\\right] ,\n$$\n\nand the quantity the two stories disagree about is the **increment**\n$\\delta_2 - \\delta_1$: the part of the fall that arrives with publication rather than\nwith the end of the sample. Arbitrage predicts $\\delta_1 \\approx 0$ and\n$\\delta_2 - \\delta_1 < 0$. Pure data mining predicts $\\delta_1 < 0$ and\n$\\delta_2 - \\delta_1 \\approx 0$.\n\n::: {.callout-important appearance=\"simple\"}\n**What this design assumes.** $\\delta_1$ and $\\delta_2$ are causal effects of publication\nonly if the publication date is as good as randomly timed with respect to a signal's own\nreturn path. That is not obviously true: authors submit when a result looks good, and\njournals publish with a lag that is itself correlated with how strong the result is. The\ndesign is therefore best read as an *event study with a pre-period*, not as a clean\nexperiment. @sec-next says what would tighten it.\n:::\n\n# The estimator {#sec-estimator}\n\n## The regression\n\n$$\nr_{it} \\;=\\; \\alpha_i \\;+\\; \\beta_1 D^{\\mathrm{post\\text{-}sample}}_{it}\n           \\;+\\; \\beta_2 D^{\\mathrm{post\\text{-}pub}}_{it} \\;+\\; \\varepsilon_{it}\n$$ {#eq-main}\n\nwhere $r_{it}$ is signal $i$'s long-short return in month $t$ in percent per month, the\ntwo $D$ variables are the window indicators, and window 1 is the omitted category — so\n$\\beta_1$ and $\\beta_2$ are read against the in-sample mean. The signal fixed effect\n$\\alpha_i$ is what makes this a *within* comparison: without it, $\\beta_2$ would partly\nreflect the fact that signals published long ago are different signals from those\npublished recently.\n\n## Absorbing the fixed effects\n\nRather than build 212 dummy columns, subtract each signal's own mean from\nevery variable:\n\n$$\n\\tilde z_{it} \\;=\\; z_{it} - \\bar z_i ,\n\\qquad \\bar z_i = \\frac{1}{T_i}\\sum_{t \\in \\mathcal{T}_i} z_{it} .\n$$\n\nBy the Frisch–Waugh–Lovell theorem [@frisch1933; @lovell1963], regressing $\\tilde r$ on\n$\\tilde D$ returns *numerically the same* $\\hat\\beta$ as the full dummy regression. This\nis not an approximation and not a shortcut for speed alone: it is the statement that\n$\\beta$ is identified from variation over time within a signal.\n\n## Clustering, and why by date\n\nTwo long-short portfolios in the same month are not independent draws. They are built\nfrom the same stocks in the same market, so a month in which value and momentum both do\nbadly moves many of them at once. Clustering by **date** allows arbitrary correlation\nwithin a month; clustering by signal would allow arbitrary correlation within a signal\nacross time, which is the wrong axis here [@petersen2009]. With\n1\\,188 months the cluster count is comfortably large, which matters\nbecause cluster-robust inference is asymptotic in the number of clusters, not the number\nof observations [@cameron2015].\n\nLet $g = 1,\\dots,G$ index months, $\\tilde X_g$ the rows of the demeaned design matrix in\nmonth $g$ and $\\hat u_g$ the residuals there. The sandwich is\n\n$$\n\\widehat{\\mathrm{Var}}(\\hat\\beta)\n\\;=\\;\nc \\,\\bigl(\\tilde X'\\tilde X\\bigr)^{-1}\n\\Bigl[\\textstyle\\sum_{g=1}^{G} \\bigl(\\tilde X_g' \\hat u_g\\bigr)\\bigl(\\tilde X_g' \\hat u_g\\bigr)'\\Bigr]\n\\bigl(\\tilde X'\\tilde X\\bigr)^{-1},\n\\qquad\nc \\;=\\; \\frac{G}{G-1}\\cdot\\frac{n-1}{n-k} .\n$$ {#eq-sandwich}\n\nThe bread is the usual $(X'X)^{-1}$; the meat is a sum of **outer products of\nwithin-cluster score sums**, which is the whole content of clustering — scores are added\nup inside a month before being squared, so correlation inside the month is absorbed\ninstead of assumed away. The finite-sample factor $c$ is the standard one. It does not\nsubtract the absorbed fixed effects from the degrees of freedom; at\n173\\,302 observations that changes the standard errors by about 0.1%.\n\n::: {#estimator .cell execution_count=5}\n``` {.python .cell-code code-fold=\"false\"}\ndef within(df, cols, by):\n    \"\"\"Demean `cols` within groups of `by`. FWL: identical to including group dummies.\"\"\"\n    return df[cols] - df.groupby(by)[cols].transform(\"mean\")\n\ndef cluster_ols(y, X, cluster):\n    \"\"\"OLS with a cluster-robust covariance matrix, written out rather than imported.\"\"\"\n    XtX_inv = np.linalg.inv(X.T @ X)\n    beta    = XtX_inv @ (X.T @ y)\n    u       = X * (y - X @ beta)[:, None]\n\n    codes = pd.factorize(cluster)[0]\n    G     = codes.max() + 1\n    meat  = np.zeros((X.shape[1], X.shape[1]))\n    for g in range(G):                       # sum scores inside a cluster, then square\n        s = u[codes == g].sum(axis=0)\n        meat += np.outer(s, s)\n\n    n, k = X.shape\n    c    = (G / (G - 1)) * ((n - 1) / (n - k))\n    V    = c * (XtX_inv @ meat @ XtX_inv)\n    return beta, V, G\n\ndef fit(sub):\n    s = sub.copy()\n    s[\"post_sample\"] = (s[\"window\"] == \"2_post_sample\").astype(float)\n    s[\"post_pub\"]    = (s[\"window\"] == \"3_post_pub\").astype(float)\n    dm = within(s, [\"ret\", \"post_sample\", \"post_pub\"], \"signal\")\n    y  = dm[\"ret\"].to_numpy()\n    X  = dm[[\"post_sample\", \"post_pub\"]].to_numpy()\n    return cluster_ols(y, X, s[\"date\"].to_numpy())\n```\n:::\n\n\n# Result 1: the three windows {#sec-result1}\n\n::: {#result1 .cell execution_count=6}\n``` {.python .cell-code code-fold=\"false\"}\nm1, m2, m3 = (table[c].mean() for c in [\"in_sample\", \"post_sample\", \"post_pub\"])\nq1, q2, q3 = (table[c].median() for c in [\"in_sample\", \"post_sample\", \"post_pub\"])\n\nbeta_f, V_f, G_f = fit(long)                                   # full panel\nbeta_m, V_m, G_m = fit(long[long[\"signal\"].isin(table.index)])  # matched signals only\nse_f, se_m = np.sqrt(np.diag(V_f)), np.sqrt(np.diag(V_m))\n\nn_down = int((table[\"post_pub\"] < table[\"in_sample\"]).sum())\nn_neg  = int((table[\"post_pub\"] < 0).sum())\nn_down2 = int((table[\"post_sample\"] < table[\"in_sample\"]).sum())\n```\n:::\n\n\n::: {#tbl-windows .cell tbl-cap='Equal-weighted across the matched signals, mean monthly long-short return.' execution_count=7}\n``` {.python .cell-code code-fold=\"true\"}\nMarkdown(f\"\"\"\n| Window | Mean, %/month | Median, %/month | Mean vs. window 1 |\n|---|---:|---:|---:|\n| 1. in the paper's own sample | {m1:.3f} | {q1:.3f} | — |\n| 2. post-sample, pre-publication | {m2:.3f} | {q2:.3f} | {100*(m2-m1)/abs(m1):+.0f}% |\n| 3. post-publication | **{m3:.3f}** | **{q3:.3f}** | **{100*(m3-m1)/abs(m1):+.0f}%** |\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=7}\n\n| Window | Mean, %/month | Median, %/month | Mean vs. window 1 |\n|---|---:|---:|---:|\n| 1. in the paper's own sample | 0.603 | 0.507 | — |\n| 2. post-sample, pre-publication | 0.437 | 0.347 | -28% |\n| 3. post-publication | **0.329** | **0.237** | **-45%** |\n\n:::\n:::\n\n\n::: {#cell-fig-windows .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\nfig, ax = plt.subplots(figsize=(6.4, 3.4))\nlabels = [\"in-sample\", \"post-sample\\npre-publication\", \"post-publication\"]\nvals = [m1, m2, m3]\nbars = ax.bar(labels, vals, color=BLUE, width=0.58, zorder=3)\nfor i, (b, v) in enumerate(zip(bars, vals)):     # one series, so one colour throughout\n    ax.text(b.get_x() + b.get_width()/2, v + 0.012, f\"{v:.3f}\", ha=\"center\", va=\"bottom\",\n            fontsize=9.5, color=INK, fontweight=\"bold\" if i == 2 else \"normal\")\nax.set_ylabel(\"mean long-short return, %/month\")\nax.set_title(f\"{N_MATCHED} published equity anomalies, 1926–2024\")\nax.grid(axis=\"x\", visible=False)\nax.set_ylim(0, max(vals) * 1.18)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The published edge, before and after publication. Same signals in all three bars.](alpha-decay_files/figure-html/fig-windows-output-1.png){#fig-windows width=1011 height=532}\n:::\n:::\n\n\nThe mean falls 45% and the median\n53%. The gap between the two is itself the\nfinding: decay is not uniform. A minority of signals survive more or less intact and pull\nthe average up, while the typical signal does worse than the average suggests.\n\n::: {#cell-fig-crosssec .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\nchg = (table[\"post_pub\"] - table[\"in_sample\"])\nfig, ax = plt.subplots(figsize=(6.4, 3.2))\ncounts, _, _ = ax.hist(chg.clip(-2.5, 2.5), bins=40, color=BLUE, alpha=0.9, zorder=3)\nax.set_ylim(0, counts.max() * 1.28)                      # headroom for the two labels\nax.axvline(0, color=INK, lw=1.2, zorder=4)\nax.axvline(chg.median(), color=ORANGE, lw=2, zorder=5)\nax.annotate(f\"median {chg.median():+.2f}\", xy=(chg.median(), counts.max() * 1.20),\n            xytext=(6, 0), textcoords=\"offset points\", ha=\"left\", va=\"center\",\n            color=ORANGE, fontsize=9, path_effects=HALO, zorder=6)\nax.annotate(\"no change\", xy=(0, counts.max() * 1.06), xytext=(6, 0),\n            textcoords=\"offset points\", ha=\"left\", va=\"center\",\n            color=MUTED, fontsize=8.5, path_effects=HALO, zorder=6)\nax.set_xlabel(\"post-publication mean − in-sample mean, %/month\")\nax.set_ylabel(\"signals\")\nax.set_title(\"Most signals lose, a few do not\")\nax.grid(axis=\"x\", visible=False)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Per-signal change from the in-sample window to the post-publication window. Left of zero is decay.](alpha-decay_files/figure-html/fig-crosssec-output-1.png){#fig-crosssec width=1011 height=500}\n:::\n:::\n\n\n151 of 189\n(80%) earn less after publication than in sample,\nand 32 (17%) have an outright negative\nmean long-short return once public. 109 were already lower in window 2 —\nthe first sign that publication is not the only thing going on.\n\n## The panel regression\n\n::: {#tbl-panel .cell tbl-cap='Equation @eq-main, signal fixed effects absorbed by within-demeaning, standard errors clustered by date.' execution_count=10}\n``` {.python .cell-code code-fold=\"true\"}\nMarkdown(f\"\"\"\n| | Full panel ({N_PANEL} signals) | Matched panel ({N_MATCHED}) |\n|---|---:|---:|\n| $\\\\beta_1$ post-sample | {beta_f[0]:+.4f} (se {se_f[0]:.4f}, t = {beta_f[0]/se_f[0]:.2f}) | {beta_m[0]:+.4f} (se {se_m[0]:.4f}, t = {beta_m[0]/se_m[0]:.2f}) |\n| $\\\\beta_2$ post-publication | **{beta_f[1]:+.4f}** (se {se_f[1]:.4f}, **t = {beta_f[1]/se_f[1]:.2f}**) | {beta_m[1]:+.4f} (se {se_m[1]:.4f}, t = {beta_m[1]/se_m[1]:.2f}) |\n| implied vs. in-sample mean | {100*beta_f[0]/abs(m1):+.0f}% and {100*beta_f[1]/abs(m1):+.0f}% | {100*beta_m[0]/abs(m1):+.0f}% and {100*beta_m[1]/abs(m1):+.0f}% |\n| clusters (months) | {G_f:,} | {G_m:,} |\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n\n| | Full panel (212 signals) | Matched panel (189) |\n|---|---:|---:|\n| $\\beta_1$ post-sample | -0.1449 (se 0.0747, t = -1.94) | -0.1277 (se 0.0752, t = -1.70) |\n| $\\beta_2$ post-publication | **-0.2718** (se 0.0531, **t = -5.12**) | -0.2518 (se 0.0548, t = -4.60) |\n| implied vs. in-sample mean | -24% and -45% | -21% and -42% |\n| clusters (months) | 1,188 | 1,188 |\n\n:::\n:::\n\n\n@mclean2016 report roughly −26% post-sample and −58% post-publication over 97 anomalies.\nThis universe is about twice as large and includes weaker and less-replicated signals,\nwhich is the obvious first explanation for the smaller numbers and is testable by\nre-running on their 97.\n\n# What this does *not* show {#sec-restriction}\n\nRead @tbl-panel quickly and the conclusion writes itself: $\\beta_2$ is sharply estimated,\n$\\beta_1$ is not, therefore publication rather than overfitting is what kills the edge.\nThat conclusion does not survive a test.\n\n\"Publication matters over and above the end of the sample\" is the restriction\n$H_0: \\beta_2 = \\beta_1$, i.e. $R\\beta = 0$ with $R = (-1,\\;1)$. The standard error of\n$R\\hat\\beta$ must come from the **same** clustered covariance matrix, and it is not the\nsum of the two individual standard errors, because $\\hat\\beta_1$ and $\\hat\\beta_2$\ncovary:\n\n$$\n\\mathrm{se}\\!\\left(\\hat\\beta_2 - \\hat\\beta_1\\right)\n= \\sqrt{R \\widehat{\\mathrm{Var}}(\\hat\\beta) R'}\n= \\sqrt{\\widehat V_{11} + \\widehat V_{22} - 2\\widehat V_{12}} .\n$$ {#eq-restriction}\n\nComparing two *t*-statistics — one significant, one not — is not a test of whether the\ncoefficients differ. @eq-restriction is.\n\n::: {#restriction .cell execution_count=11}\n``` {.python .cell-code code-fold=\"false\"}\nR = np.array([-1.0, 1.0])\n\ndef restriction(beta, V):\n    diff = R @ beta\n    se   = np.sqrt(R @ V @ R)\n    return diff, se, diff / se\n\ndiff_f, sed_f, td_f = restriction(beta_f, V_f)\ndiff_m, sed_m, td_m = restriction(beta_m, V_m)\ncorr_f = V_f[0, 1] / np.sqrt(V_f[0, 0] * V_f[1, 1])\n```\n:::\n\n\n::: {#tbl-restriction .cell tbl-cap='Testing $\\beta_2 = \\beta_1$ on the same clustered covariance.' execution_count=12}\n``` {.python .cell-code code-fold=\"true\"}\nMarkdown(f\"\"\"\n| | $\\\\hat\\\\beta_2 - \\\\hat\\\\beta_1$, %/month | se | t |\n|---|---:|---:|---:|\n| Full panel | {diff_f:+.4f} | {sed_f:.4f} | **{td_f:.2f}** |\n| Matched {N_MATCHED} | {diff_m:+.4f} | {sed_m:.4f} | {td_m:.2f} |\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=12}\n\n| | $\\hat\\beta_2 - \\hat\\beta_1$, %/month | se | t |\n|---|---:|---:|---:|\n| Full panel | -0.1269 | 0.0761 | **-1.67** |\n| Matched 189 | -0.1241 | 0.0755 | -1.64 |\n\n:::\n:::\n\n\nThe incremental effect of publication, over and above the decline that had already\nhappened by the time the original sample ended, is **not significant at the 5% level**\n(|t| = 1\\.67 against a 1.96 critical value). The estimated\ncorrelation between $\\hat\\beta_1$ and $\\hat\\beta_2$ is\n0\\.33, which is why the difference is less precisely estimated than\n$\\hat\\beta_2$ alone.\n\n::: {.callout-warning appearance=\"simple\"}\n**The sentence not to write.** \"Publication, not overfitting, is what kills the edge.\"\nThe point estimates are consistent with it. The data do not support it at conventional\nlevels, and the three-window design as run here does not separate the arbitrage channel\nfrom the data-mining channel on this universe.\n\nWhat can be said: the post-publication decline is precisely estimated, the post-sample\ndecline is not, and the difference between them is not sharp enough to claim. That is a\nweaker headline and a stronger piece of work, because the restriction was tested rather\nthan eyeballed.\n:::\n\n# How much of this rests on someone else's numbers? {#sec-rebuild}\n\nEverything above is computed from 189 return series that somebody else constructed. That\nis a dependency, and an untested one. Two signals are therefore rebuilt from\nsecurity-level CRSP data and scored month by month against the published versions: `Size`,\nabout the simplest anomaly there is, and `Mom12m`, which has a formation window, a skip\nmonth and overlapping holding periods and is therefore easy to get subtly wrong.\n\nThe pull (`03_crsp_pull.py`) and the rebuild (`04_build_anomalies.py`) need a WRDS\nsubscription. This section does not: it reads the committed result files.\n\n## Portfolio construction, written out\n\nAt each formation month $m$ the cross-section is sorted on the signal and cut into\n$n = 1/q$ buckets, where $q$ comes from `SignalDoc` — $q = 0.5$ for `Size` (halves, as in\n@banz1981, who splits the market in two and does not sort deciles) and $q = 0.1$ for\n`Mom12m`. For a bucket $B_m$ and a horizon $h$,\n\n$$\n\\bar r^{\\,B}_{m,h} \\;=\\;\n\\frac{\\sum_{i \\in B_m} w_{i,m}\\, r_{i,\\,m+h}}{\\sum_{i \\in B_m} w_{i,m}} ,\n\\qquad\n\\mathrm{LS}^{(h)}_{m} \\;=\\; s \\cdot\n\\Bigl( \\bar r^{\\,\\mathrm{top}}_{m,h} - \\bar r^{\\,\\mathrm{bot}}_{m,h} \\Bigr),\n$$\n\nwith $w_{i,m} = 1$ for equal weighting and $w_{i,m} = \\mathrm{mthcap}_{i,m}$ for value\nweighting, and $s = \\pm 1$ the sign from `SignalDoc` — **$s = -1$ for `Size`**, because\nthe anomaly is small minus big and reversing it produces a beautifully significant result\nwith the wrong label on it.\n\n`Portfolio Period` is a holding period with overlapping cohorts [@jegadeesh1993]: the\nreturn booked in calendar month $c$ averages the cohorts formed at\n$c-1, \\dots, c-H$,\n\n$$\n\\mathrm{LS}_{c} \\;=\\; \\frac{1}{H}\\sum_{h=1}^{H} \\mathrm{LS}^{(h)}_{\\,c-h} .\n$$ {#eq-cohorts}\n\nThe momentum signal itself is the twelve-month return ending one month before formation:\n\n$$\ns^{\\mathrm{mom}}_{i,m}\n\\;=\\;\n\\exp\\!\\Biggl(\\;\\sum_{\\tau = m-k-11}^{\\,m-k} \\log\\bigl(1 + r_{i\\tau}\\bigr)\\Biggr) - 1,\n\\qquad k = 1 ,\n$$ {#eq-mom}\n\ndefined only where the stock has a contiguous monthly record across the window, and\n`Size` is simply $s^{\\mathrm{size}}_{i,m} = \\log(\\mathrm{mthcap}_{i,m})$.\n\n## The verdict\n\n::: {#rebuild-load .cell execution_count=13}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"read the committed rebuild results\"}\ndef load_rebuild(name, col):\n    df = pd.read_csv(OUT / f\"rebuild_{name}.csv\")\n    o  = df.dropna(subset=[col, \"theirs\"]).copy()\n    o[\"gap\"] = o[col] - o[\"theirs\"]\n    o[\"year\"] = [ym(v)[0] for v in o[\"mi\"]]\n    return o\n\nreb = {\"Size\": load_rebuild(\"Size\", \"mine\"),\n       \"Mom12m\": load_rebuild(\"Mom12m\", \"mine_hold1\")}\nCOL = {\"Size\": \"mine\", \"Mom12m\": \"mine_hold1\"}\n\ndef gap_t(o):\n    g = o[\"gap\"].to_numpy()\n    return g.mean(), g.std(ddof=1) / np.sqrt(len(g))\n\ndef corr(o, name):\n    return float(np.corrcoef(o[COL[name]], o[\"theirs\"])[0, 1])\n```\n:::\n\n\n::: {#tbl-rebuild .cell tbl-cap='Rebuilt from CRSP against the published series, on the common overlap window.' execution_count=14}\n``` {.python .cell-code code-fold=\"true\"}\nrows = []\nfor name, conv in [(\"Size\", \"EW, halves, hold 12\"), (\"Mom12m\", \"EW, deciles, hold 1\")]:\n    o = reb[name]; mg, sg = gap_t(o)\n    rows.append(f\"| **{name}** ({conv}) | {o[COL[name]].mean():.3f} | \"\n                f\"{o['theirs'].mean():.3f} | {mg:+.3f} (t = {mg/sg:+.2f}) | \"\n                f\"{corr(o, name):.3f} | {len(o):,} |\")\n\nMarkdown(\"| | rebuilt, %/month | Chen–Zimmermann | difference | corr | months |\\n\"\n         \"|---|---:|---:|---:|---:|---:|\\n\" + \"\\n\".join(rows))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=14}\n| | rebuilt, %/month | Chen–Zimmermann | difference | corr | months |\n|---|---:|---:|---:|---:|---:|\n| **Size** (EW, halves, hold 12) | 0.324 | 0.322 | +0.002 (t = +0.16) | 0.992 | 1,182 |\n| **Mom12m** (EW, deciles, hold 1) | 0.791 | 0.899 | -0.107 (t = -1.82) | 0.972 | 1,174 |\n:::\n:::\n\n\n::: {#cell-fig-rebuild .cell execution_count=15}\n``` {.python .cell-code code-fold=\"true\"}\nfig, axes = plt.subplots(1, 2, figsize=(7.6, 3.4))\n\n# Identity is carried by line style as well as hue, so the panels survive greyscale\n# printing and colour-vision deficiency without labels sitting on top of the data.\nfor ax, name in zip(axes, [\"Size\", \"Mom12m\"]):\n    o = reb[name]; x = mi_to_ts(o[\"mi\"])\n    a = (1 + o[COL[name]] / 100).cumprod().to_numpy()\n    b = (1 + o[\"theirs\"] / 100).cumprod().to_numpy()\n    ax.plot(x, b, color=ORANGE, lw=1.5, ls=(0, (4, 2)), label=\"Chen–Zimmermann\", zorder=2)\n    ax.plot(x, a, color=BLUE,   lw=1.1, label=\"rebuilt from CRSP\", zorder=3)\n    ax.set_yscale(\"log\"); ax.set_title(name)\n    ax.grid(axis=\"x\", visible=False); ax.margins(x=0.02)\n    ax.legend(loc=\"upper left\", fontsize=8)\n\naxes[0].set_ylabel(\"cumulative long-short, log scale\")\naxes[0].annotate(\"the two lines coincide\", xy=(0.50, 0.08), xycoords=\"axes fraction\",\n                 fontsize=8.5, color=MUTED)\naxes[1].annotate(\"same turning points,\\nshallower slope\", xy=(0.52, 0.06),\n                 xycoords=\"axes fraction\", fontsize=8.5, color=MUTED)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Cumulative long-short value of one dollar, log scale. Rebuilt from CRSP against the published series.](alpha-decay_files/figure-html/fig-rebuild-output-1.png){#fig-rebuild width=1202 height=531}\n:::\n:::\n\n\n**Size reproduces essentially exactly** — a difference of\n\\+0\\.002 %/month over\n1\\,182 months, correlation\n0\\.992. In @fig-rebuild the two lines are hard to\ntell apart across a century.\n\n**Momentum reproduces in shape and comes in light in level.** The right-hand panel shows\ntwo lines with the same turning points and different slopes, which on a log scale is the\nsignature of a roughly constant per-month shortfall rather than one bad episode.\n\n## Is the momentum gap real?\n\n::: {#gap-diagnostic .cell execution_count=16}\n``` {.python .cell-code code-fold=\"false\"}\no = reb[\"Mom12m\"]\nmg, sg = gap_t(o)\nsd_gap = o[\"gap\"].std(ddof=1)\n\n# 1. thin pre-1963 data, when CRSP covers NYSE only?\npre, post = o[o[\"year\"] < 1963], o[o[\"year\"] >= 1963]\n(mpre, spre), (mpost, spost) = gap_t(pre), gap_t(post)\n\n# 2. a uniform implementation difference, present every month?\nshare_below = (o[\"gap\"] < 0).mean()\n\n# 3. or a tail?\nworst   = o.reindex(o[\"gap\"].abs().sort_values(ascending=False).index)\nshare60 = worst.head(60)[\"gap\"].sum() / len(o) / mg\ncut     = o[\"gap\"].abs().quantile(0.90)\ntrim_all  = o[o[\"gap\"].abs() <= cut][\"gap\"].mean()\ncut_pre   = pre[\"gap\"].abs().quantile(0.90)\ntrim_pre  = pre[pre[\"gap\"].abs() <= cut_pre][\"gap\"].mean()\ncorr_abs  = float(np.corrcoef(o[\"gap\"].abs(), o[\"theirs\"].abs())[0, 1])\n```\n:::\n\n\n**First, is it even distinguishable from zero?** A momentum long-short series is volatile\nand so is the month-by-month difference between two implementations of one. The gap has a\nstandard deviation of 2\\.03 %/month, so a mean of\n\\-0\\.107 over 1\\,174 months carries\n**t = \\-1\\.82**. Before 1963 it is t = \\-0\\.74;\nfrom 1963 on, t = \\-1\\.94. Neither era rejects equality.\n\n**Hypothesis 1: thin early data.** CRSP covers NYSE only until mid-1962, so the natural\nguess is that the gap sits before 1963 and the modern period replicates cleanly.\n*Rejected.* The gap is \\-0\\.092 before 1963 and\n\\-0\\.116 after — essentially identical.\n\n**Hypothesis 2: a uniform implementation difference.** If a slightly different screen\nproduced a slightly different portfolio every month, the sign of the difference would be\npersistent. *Rejected.* The rebuilt series is below the published one in\n53\\.0% of months, a coin flip.\n\n**What it actually is: a tail.** The 60 largest-|gap| months — 5% of the sample — carry\n100% of the mean difference. Trim the largest decile of months\nand the full-sample gap falls to \\-0\\.051, while the pre-1963 gap\nflips sign to \\+0\\.068. And the absolute gap correlates\n0\\.37 with the absolute size of that month's published return: the\ndiscrepancy is largest exactly when momentum itself moves most.\n\n::: {#tbl-worst .cell tbl-cap='The eight months that carry the momentum difference.' execution_count=17}\n``` {.python .cell-code code-fold=\"true\"}\nrows = []\nfor _, r in worst.head(8).iterrows():\n    y, m = ym(r[\"mi\"])\n    rows.append(f\"| {y}-{m:02d} | {r['mine_hold1']:.2f} | {r['theirs']:.2f} | {r['gap']:+.2f} |\")\nMarkdown(\"| Month | rebuilt | published | difference |\\n|---|---:|---:|---:|\\n\"\n         + \"\\n\".join(rows))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=17}\n| Month | rebuilt | published | difference |\n|---|---:|---:|---:|\n| 1939-11 | -1.42 | 15.84 | -17.27 |\n| 1932-12 | -0.99 | 15.12 | -16.11 |\n| 1939-09 | -92.69 | -78.23 | -14.47 |\n| 1942-01 | -27.06 | -15.32 | -11.74 |\n| 1943-01 | 4.78 | 16.19 | -11.41 |\n| 1931-01 | -26.37 | -16.16 | -10.21 |\n| 1933-06 | -7.88 | 1.86 | -9.74 |\n| 1933-05 | -40.68 | -50.22 | +9.54 |\n:::\n:::\n\n\nThese name themselves. 2009-03 is the worst month on record for momentum, and 1939-09 is\nthe outbreak-of-war rebound — both are momentum crashes in the sense of @daniel2016, when\npast losers surge and the extreme deciles turn over violently. In exactly those months a\nsingle imputed price, or one stock that delists in the middle of a holding period, moves a\nbucket mean by percentage points, and two implementations of a decile sort must part\ncompany. @shumway1997 is the classic statement of how much the treatment of disappearing\nstocks matters.\n\n::: {.callout-note appearance=\"simple\"}\n**The line not crossed.** No screen variants were tried. Closing the remaining\n0\\.107 %/month by searching filter combinations until the number\nmatches would be curve-fitting the replication itself — the same behaviour this project\nexists to measure. The position without it is defensible: one signal reproduces exactly,\nthe other reproduces to within sampling error.\n:::\n\n## The bug this caught, and why correlation hid it {#sec-skip}\n\n`SignalDoc` defines `Mom12m` over \"months t-12 and t-1\". **Month $t$ is excluded** — the\n$k = 1$ in @eq-mom. The first implementation used $m-11,\\dots,m$ instead, which pulls\nshort-term reversal [@jegadeesh1990] into a momentum signal: last month's return is\nnegatively autocorrelated, so including it does not add noise, it adds an effect of the\nopposite sign.\n\n::: {#skip .cell execution_count=18}\n``` {.python .cell-code code-fold=\"false\"}\n# `mine` and `mine_noskip` are both the documented three-month holding period. They\n# differ in one thing only: whether month t is inside the formation window. Compare them\n# on the same rows, so the holding period cannot be doing the work.\nns = (pd.read_csv(OUT / \"rebuild_Mom12m.csv\")\n        .dropna(subset=[\"mine\", \"mine_noskip\", \"theirs\"]))\nmean_skip   = ns[\"mine\"].mean()\nmean_noskip = ns[\"mine_noskip\"].mean()\nmean_theirs = ns[\"theirs\"].mean()\ncorr_noskip = float(np.corrcoef(ns[\"mine_noskip\"], ns[\"theirs\"])[0, 1])\n```\n:::\n\n\nHolding everything else fixed at the documented three-month holding period, dropping the\nskip takes the long-short mean from 0\\.652 to\n0\\.459 %/month, against a published\n0\\.899. Rebalanced monthly, where no cohort skips at all, it went\nto −0.009 %/month: the premium gone entirely.\n\n**And the correlation never flinched: 0\\.974, peaking at lag 0.**\nThat is the lesson worth keeping. A correlation confirms that the wiring is right and the\ntiming is right; it rules out a merge error or an off-by-one in the calendar. It says\nnothing about whether the *signal definition* is right, because a wrong window is still\nmostly the same portfolio. Only the level catches this.\n\n# What the design cannot do, and what comes next {#sec-next}\n\n## Two-way fixed effects under staggered treatment\n\nPublication arrives at a different date for every signal, so @eq-main is a two-way fixed\neffects regression with staggered adoption. @goodmanbacon2021 shows that such an estimator\nis a variance-weighted average of all possible two-group comparisons, **including\ncomparisons that use already-treated signals as controls for later-treated ones**. When the\ntreatment effect varies across signals or evolves over time — and decay that continues for\nyears after publication is precisely a treatment effect that evolves — those comparisons\nenter with the wrong sign and the weighted average need not lie inside the range of the\ntrue effects [@dechaisemartin2020].\n\nThat is a concrete reason to doubt $\\hat\\beta_2$ as a causal estimate, separate from the\nidentification worry in @sec-design. The repairs are known: @callaway2021 estimate group-\ntime effects using only not-yet-treated units as controls, @sun2021 do the interaction-\nweighted version for event studies, and @borusyak2024 give the efficient imputation\nestimator. @roth2023 survey the choice. **This is the next thing to build**, and it should\nchange the number.\n\n## Why not regression discontinuity\n\nPublication is a date, which invites the thought that a discontinuity design applies. It\ndoes not. RDD needs a running variable with a cutoff and units that cannot precisely\nmanipulate their position around it. Here the \"running variable\" is calendar time, the\ncutoff is anticipated — working papers circulate for years before a journal issue appears —\nand authors have some control over timing. Anticipation alone is fatal: informed traders\nacting on a working paper push part of the decay *before* the event, which biases the\nestimate towards zero and makes the post-publication decline a **lower bound** on the true\none. The honest labels are interrupted time series and event study; the sharper version is\nstaggered difference-in-differences, above.\n\n## How fast, and to what floor\n\nA three-window average says the edge fell. It does not say how quickly, or whether it fell\nto zero. Two routes:\n\n$$\n\\alpha_t \\;=\\; \\phi + (\\alpha_0 - \\phi)\\,e^{-\\lambda t}\n\\qquad\\Longrightarrow\\qquad\n\\text{half-life} \\;=\\; \\frac{\\ln 2}{\\lambda},\n$$\n\nfitted per signal by nonlinear least squares, is the simple version, and $\\phi$ is the\n**floor** — which @grossman1980 says should be strictly positive, so estimating it is a\ntest of that prediction rather than an accounting exercise. The upgrade is a local-level\nstate-space model,\n\n$$\nr_t = \\alpha_t + \\varepsilon_t, \\qquad\n\\alpha_t = \\alpha_{t-1} + \\eta_t, \\qquad\n\\varepsilon_t \\sim N(0,\\sigma^2_\\varepsilon),\\;\\; \\eta_t \\sim N(0,\\sigma^2_\\eta),\n$$\n\nestimated by the Kalman filter and smoother [@durbin2012], which returns an $\\alpha_t$ path\nwith a credible interval instead of a curve fitted by eye. A Markov-switching version\n[@hamilton1989] would give a \"probability the edge is still alive\" series.\n\n## Who dies fast, and why\n\nThe cross-sectional question is where the arbitrage story becomes falsifiable: decay should\nbe fastest where arbitrage is cheapest. The proxies — Amihud illiquidity [@amihud2002],\nmarket capitalisation, idiosyncratic volatility, short interest, institutional ownership —\nare all computable from the CRSP panel this project already built, which is the reason\n@sec-rebuild exists. Independently, `contrib.global_factor` [@jensen2023] carries 153\ncharacteristics across 93 countries, which turns the same hypothesis into a cross-country\ntest with completely different identifying variation.\n\n## Open items, stated plainly\n\n- Re-run on the @mclean2016 97 to see whether the weaker channel separation is a\n  universe-composition effect.\n- Replace @eq-main with @callaway2021 and @sun2021 and report how much the estimate moves.\n- An event-time plot: average return by months-since-publication, which is the picture\n  @eq-main compresses into two numbers.\n- Gross profitability [@novymarx2013] as a third rebuilt signal — it needs Compustat and\n  the CCM link, so it is a genuinely harder test of the pipeline than either signal here.\n\n# Reproducing this document {#sec-repro}\n\n```bash\n# Sections 1–6 need only the two free Chen–Zimmermann files in data/\nquarto render paper/alpha-decay.qmd --to html\n\n# Section 7 reads committed result files and needs nothing.\n# To regenerate those from source (WRDS subscription required):\npython 03_crsp_pull.py\npython 04_build_anomalies.py\n```\n\n::: {#verify .cell execution_count=19}\n``` {.python .cell-code code-fold=\"false\"}\n# The three-window means recomputed here must match the ones 02_decay_panel.py wrote.\n# If this assertion ever fires, the script and the paper have drifted apart and one of\n# them is wrong -- which is the entire reason the check is in the document.\nsaved = pd.read_csv(OUT / \"result1_windows.csv\", index_col=0)\nassert saved.shape[0] == N_MATCHED, (saved.shape[0], N_MATCHED)\nfor c in [\"in_sample\", \"post_sample\", \"post_pub\"]:\n    np.testing.assert_allclose(saved[c].mean(), table[c].mean(), rtol=1e-10)\nprint(f\"verified against output/result1_windows.csv: {N_MATCHED} signals, three windows match\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nverified against output/result1_windows.csv: 189 signals, three windows match\n```\n:::\n:::\n\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "alpha-decay_files"
    ],
    "filters": [],
    "includes": {}
  }
}